### ISSUE TITLE
Unblock UI is not included.

### ISSUE THREAD

**Issue by arelberg** [joseninogarcia/WebBlock#1]
Hi Sir Nino, 

I would like to request for the Unblock UI code for this one.  Seems that the plugin does not include the Unblock UI or close the whole pop up. Thank you!

**Comment by joseninogarcia** [comment]
Sorry about that, will include this now. Thanks for sending issues with regards to this matter.

**Comment by joseninogarcia** [comment]
Done. Thanks :)
